version: '3'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: openai

  rabbitmq:
    image: rabbitmq:3.8.17-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    expose:
      - 9090
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
    links:
      - prometheus:prometheus
    expose:
      - 3000
    ports:
      - 3000:3000

  trace:
    container_name: trace
    image: openzipkin/zipkin
    restart: always
    ports:
      - 9411:9411
    expose:
      - 9411

  logspout:
    image: gliderlabs/logspout:v3
    command: 'udp://logstash:9600'
    networks:
      - elk
    links:
      - logstash
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    depends_on:
      - elasticsearch
      - logstash
      - kibana


  logstash:
    image: logstash:7.17.10
    environment:
      - STDOUT=true
    links:
      - elasticsearch
    networks:
      - elk
    depends_on:
      - elasticsearch
      - kibana
    command: 'logstash -e "input { udp { port => 9600 } } output { elasticsearch { hosts => elasticsearch } }"'

  kibana:
    image: kibana:7.17.10
    container_name: kibana
    restart: always
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk

  elasticsearch:
    image: elasticsearch:7.17.10
    container_name: elasticsearch
    restart: always
    volumes:
      - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - elk
volumes:
  elastic_data: {}

networks:
  elk: