openAi:
  token: ${OPENAI_TOKEN}
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: openai
      username: root
      password: example
      uuid-representation: standard

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_ID}
            client-secret: ${GITHUB_SECRET}
            scope:
              - user:email
              - read:user