resilience4j:
  circuitbreaker:
    instances:
      aiMedicalAppointment:
        slidingWindowSize: 30
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 20
        waitDurationInOpenState: 30s
        failureRateThreshold: 80
        ignoreExceptions:
          - org.springframework.web.client.HttpClientErrorException

openAi:
  token: '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'
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: openai
      username: root
      password: example
      uuid-representation: standard

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: '515106661034-44kuvah7uajmb56vc0lkoufeireu1g8d.apps.googleusercontent.com'
            client-secret: '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'
            scope:
              - email
              - profile
          github:
            client-id: '318fe0b379c2c7bc2261'
            client-secret: '00f891362dc7f7a93f1004896fa8451d7fa64b62'
            scope:
              - user:email
              - read:user

