resilience4j:
  circuitbreaker:
    instances:
      aiMedicalAppointment:
        slidingWindowSize: 30
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 30s
        failureRateThreshold: 80

openAi:
  token: ${OPENAI_TOKEN}
spring:
  application:
    name: ai-medical-appointment
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: openai
      username: root
      password: example
      uuid-representation: standard

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_ID}
            client-secret: ${GITHUB_SECRET}
            scope:
              - user:email
              - read:user

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'